image: docker:git
services:
- docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - git clone https://github.com/CentOS/sig-cloud-instance-images.git instance-images --depth 1 -b CentOS-7


clone_base:
  script:
    - docker pull centos:7
    - docker tag centos:7 registry.gitlab.com/gbraad/centos:7
    - docker push registry.gitlab.com/gbraad/centos:7
  only:
    - master

clone_tools:
  script:
    - docker pull centos/tools:latest
    - docker tag centos/tools:latest registry.gitlab.com/gbraad/centos:tools
    - docker push registry.gitlab.com/gbraad/centos:tools
  only:
    - master

build_base:
  script:
    - docker build -t registry.gitlab.com/gbraad/centos:base7 ./instance-images/docker/
    - docker push registry.gitlab.com/gbraad/centos:base7
  only:
    - master
